name: Docker

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  setup:
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
      build-date: ${{ steps.build-date.outputs.build-date }}
    runs-on: ubuntu-latest
    steps:
    - id: tag
      run: |
        tag="stellar/friendbot:${{ github.sha }}"
        echo "tag=$tag" | tee -a $GITHUB_OUTPUT
    - id: build-date
      run: |
        date="$(date -u  +%FT%TZ)"
        echo "build-date=$build_date" | tee -a $GITHUB_OUTPUT

  build:
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: >
        docker build --pull
        -t "${{ needs.setup.outputs.tag }}"
        --label org.opencontainers.image.created="${{ needs.setup.outputs.date}}"
        --label org.opencontainers.image.revision="${{ github.sha }}"
        .
    - run: |
        docker save "${{ needs.setup.outputs.tag }}" -o /tmp/image
    - uses: actions/upload-artifact@v4
      with:
        name: image-amd64
        path: /tmp/image
        # 30 days is how long environments jobs can stay open for approval to run if they require an approver.
        retention-days: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') && '30' || '7' }}

  push:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [setup, build]
    permissions:
      statuses: write
    environment: dockerhub
    concurrency: dockerhub
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v5
      with:
        pattern: image-amd64
        path: /tmp/
    - run: |
        docker load -i /tmp/image
    - uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
      with:
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - run: |
        docker push ${{ needs.setup.outputs.tag }}
    - uses: actions/github-script@v5
      with:
        script: |
          github.rest.repos.createCommitStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            sha: '${{ github.sha }}',
            state: 'success',
            context: 'docker.io/${{ needs.setup.outputs.tag }}',
            description: 'Available',
          });

  push-ecr-public:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [setup, build]
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v5
      with:
        pattern: image-amd64
        path: /tmp/
    - run: |
        docker load -i /tmp/image
    - name: ECR Login via OIDC
      id: ecr-login
      uses: stellar/actions/sdf-ecr-login@main
      with:
        aws-oidc-role: ${{ secrets.AWS_GITHUB_OIDC_ROLE }}       # required
        aws-ecr-login-role: ${{ secrets.AWS_ECR_LOGIN_ROLE }}     # required
        aws-region: 'us-east-1'
        login-public-ecr: 'true'
    - name: Push image to Amazon ECR public repository
      env:
        ECR_PUBLIC_REGISTRY: ${{ steps.ecr-login.outputs.ecr-public-registry }}
        REGISTRY_ALIAS: stellar
        REPOSITORY: friendbot
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker tag "${{ needs.setup.outputs.tag }}" "$ECR_PUBLIC_REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG"
        docker push "$ECR_PUBLIC_REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG"
