name: Quickstart

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: '0 18 * * *' # Daily at 10am PT (6pm UTC)

permissions: # no permissions are required by this workflow

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_protected == 'true' && github.sha || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: stellar/quickstart/.github/workflows/build.yml@main
    with:
      images: |
        [
          {
            "tag": "latest-with-pr",
            "inherit": "latest",
            "deps": [
              { "name": "friendbot", "repo": "${{ github.repository }}", "ref": "${{ github.event.pull_request.head.sha || github.sha }}", "options": { "pkg": "github.com/stellar/friendbot" } }
            ]
          },
          {
            "tag": "testing-with-pr",
            "inherit": "testing",
            "deps": [
              { "name": "friendbot", "repo": "${{ github.repository }}", "ref": "${{ github.event.pull_request.head.sha || github.sha }}", "options": { "pkg": "github.com/stellar/friendbot" } }
            ]
          },
          {
            "tag": "nightly-with-pr",
            "inherit": "nightly",
            "deps": [
              { "name": "friendbot", "repo": "${{ github.repository }}", "ref": "${{ github.event.pull_request.head.sha || github.sha }}", "options": { "pkg": "github.com/stellar/friendbot" } }
            ]
          },
          {
            "tag": "nightly-next-with-pr",
            "inherit": "nightly-next",
            "deps": [
              { "name": "friendbot", "repo": "${{ github.repository }}", "ref": "${{ github.event.pull_request.head.sha || github.sha }}", "options": { "pkg": "github.com/stellar/friendbot" } }
            ]
          }
        ]
      archs: '["amd64"]'
